on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    environment: prd
    steps:
      - name: Install envbed
        shell: bash
        run: sudo curl -sfL https://raw.githubusercontent.com/igtm/envbed/master/install.sh | sudo sh -s -- -b=/usr/local/bin -v=v0.0.1
      - uses: actions/checkout@master
      - name: set production environment variables
        shell: bash
        run: envbed -f chrome-extension-public/pages/constants.example.js -p MDCLIENT__ -o chrome-extension-public/pages/constants.js
      - name: Run build
        shell: bash
        run: make zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: package.zip
